"""
Helper Utilities for CampaignPilot AI
Includes string formatting, data conversions, and report generation functions.
"""

import json
import pandas as pd
from typing import Dict, Any

def format_currency(amount: float, currency_symbol: str = "₹") -> str:
    """Format numeric budget into readable currency format."""
    try:
        val = float(amount)
        if currency_symbol in ["₹", "Rs", "INR"]:
            return f"₹{val:,.2f}"
        return f"${val:,.2f}"
    except (ValueError, TypeError):
        return f"{currency_symbol}{amount}"

def campaign_to_markdown(campaign_data: Dict[str, Any]) -> str:
    """Convert full campaign plan output into a beautifully formatted Markdown report."""
    req = campaign_data.get("requirements", {})
    aud = campaign_data.get("audience", {})
    strat = campaign_data.get("strategy", {})
    content = campaign_data.get("content", [])
    budget = campaign_data.get("budget", {})
    schedule = campaign_data.get("schedule", [])
    kpis = campaign_data.get("kpis", {})

    md = f"""# 🚀 CampaignPilot AI - Marketing Campaign Plan

## 📌 Campaign Overview
- **Brand / Product:** {req.get('product_name', 'N/A')}
- **Objective:** {req.get('objective', 'N/A')}
- **Target Audience:** {req.get('target_audience', 'N/A')} ({req.get('age_group', 'N/A')}, {req.get('location', 'N/A')})
- **Budget:** {req.get('budget', 'N/A')}
- **Duration:** {req.get('duration_days', 'N/A')} Days
- **Platforms:** {', '.join(req.get('platforms', []))}
- **Brand Tone:** {req.get('tone', 'N/A')}
- **Mode:** {'Demo Mode' if campaign_data.get('is_demo', False) else 'Live AI Generated'}

---

## 🎯 Target Audience Analysis
- **Primary Persona:** {aud.get('primary_audience', 'N/A')}
- **Secondary Persona:** {aud.get('secondary_audience', 'N/A')}
- **Key Interests:** {', '.join(aud.get('audience_interests', [])) if isinstance(aud.get('audience_interests'), list) else aud.get('audience_interests', 'N/A')}
- **Customer Pain Points:** {', '.join(aud.get('pain_points', [])) if isinstance(aud.get('pain_points'), list) else aud.get('pain_points', 'N/A')}
- **Buying Motivations:** {aud.get('buying_motivation', 'N/A')}
- **Recommended Communication Style:** {aud.get('recommended_communication_style', 'N/A')}

---

## 💡 Core Marketing Strategy
- **Campaign Objective:** {strat.get('campaign_objective', 'N/A')}
- **Unique Campaign Idea:** {strat.get('unique_campaign_idea', 'N/A')}
- **Key Message / Tagline:** "{strat.get('key_message', 'N/A')}"
- **Core Marketing Strategy:** {strat.get('core_strategy', 'N/A')}
- **Content Mix:** {strat.get('content_mix', 'N/A')}

---

## ✍️ Generated Content Plan ({len(content)} Posts)
"""
    for idx, post in enumerate(content, 1):
        md += f"""
### Post {idx}: [{post.get('platform', 'Social')}] - {post.get('content_type', 'Post')}
- **Topic:** {post.get('topic', 'N/A')}
- **Hook:** {post.get('hook', 'N/A')}
- **Caption:** {post.get('caption', 'N/A')}
- **Call to Action (CTA):** {post.get('cta', 'N/A')}
- **Hashtags:** {post.get('hashtags', 'N/A')}
"""

    md += f"""
---

## 💰 Budget Allocation
**Total Budget:** {budget.get('currency', '₹')}{budget.get('total_budget', 0):,}

| Category | Amount | Percentage | Description |
| :--- | :--- | :--- | :--- |
"""
    allocations = budget.get("allocations", [])
    for alloc in allocations:
        md += f"| {alloc.get('category')} | {budget.get('currency', '₹')}{alloc.get('amount', 0):,} | {alloc.get('percentage')}% | {alloc.get('description', '')} |\n"

    md += f"""
---

## 📅 Campaign Schedule ({len(schedule)} Entries)

| Day / Date | Platform | Content Type | Content Topic | Objective |
| :--- | :--- | :--- | :--- | :--- |
"""
    for entry in schedule:
        md += f"| Day {entry.get('day', 1)} | {entry.get('platform', '')} | {entry.get('content_type', '')} | {entry.get('topic', '')} | {entry.get('objective', '')} |\n"

    md += f"""
---

## 📈 Recommended KPI Targets (AI Estimates)
*Note: KPI targets are AI-generated planning estimates and are not guaranteed campaign results.*

"""
    kpi_list = kpis.get("recommendations", [])
    for kpi in kpi_list:
        md += f"- **{kpi.get('kpi_name')}**: Target range `{kpi.get('target_range')}` — *{kpi.get('why_it_matters')}* (Measured via: {kpi.get('how_measured')})\n"

    md += "\n---\n*Report generated by CampaignPilot AI System.*"
    return md

def campaign_schedule_to_csv(schedule_list: list) -> str:
    """Convert schedule list to downloadable CSV string."""
    df = pd.DataFrame(schedule_list)
    return df.to_csv(index=False)
