"""
Campaign Orchestrator Agent for CampaignPilot AI
------------------------------------------------
COLLEGE PROJECT CONCEPT: AGENTIC ORCHESTRATION
Unlike a basic single-prompt LLM chatbot, an Agentic AI system receives a high-level goal,
decomposes it into specialized sub-tasks, delegates each sub-task to a specialized autonomous agent,
and synthesizes the individual agent outputs into a unified master output.

Workflow Pipeline:
USER INPUT -> ORCHESTRATOR -> AUDIENCE AGENT -> STRATEGY AGENT -> CONTENT AGENT -> BUDGET AGENT -> SCHEDULER AGENT -> KPI AGENT -> FINAL PLAN
"""

import time
from typing import Dict, Any, Callable, Optional, Generator

from agents.audience_agent import AudienceAgent
from agents.strategy_agent import StrategyAgent
from agents.content_agent import ContentAgent
from agents.budget_agent import BudgetAgent
from agents.scheduler_agent import SchedulerAgent
from agents.kpi_agent import KPIAgent
from utils.demo_data import generate_generic_demo, get_campus_brew_demo
from utils.api import get_openai_key

class CampaignOrchestrator:
    """
    Master Orchestrator Agent responsible for executing the agent pipeline
    and broadcasting real-time step execution updates to the frontend.
    """
    def __init__(self, api_key: Optional[str] = None, demo_mode: bool = False):
        self.api_key = api_key
        self.demo_mode = demo_mode
        
        # Instantiate sub-agents
        self.audience_agent = AudienceAgent(api_key)
        self.strategy_agent = StrategyAgent(api_key)
        self.content_agent = ContentAgent(api_key)
        self.budget_agent = BudgetAgent(api_key)
        self.scheduler_agent = SchedulerAgent(api_key)
        self.kpi_agent = KPIAgent(api_key)

    def run_pipeline(
        self,
        campaign_reqs: Dict[str, Any],
        status_callback: Optional[Callable[[str, int], None]] = None
    ) -> Dict[str, Any]:
        """
        Executes the agentic pipeline sequentially while updating progress callback.
        """
        # Check if Demo Mode should be enforced
        effective_key = get_openai_key(self.api_key)
        is_demo = self.demo_mode or (not effective_key)

        if is_demo:
            # Simulate real-time agent execution visual steps for Demo Mode
            steps = [
                ("Campaign requirements analyzed", 15),
                ("Target audience analyzed by Audience Agent", 30),
                ("Strategy generated by Strategy Agent", 45),
                ("Content generated by Content Agent", 60),
                ("Budget allocated by Budget Agent", 75),
                ("Schedule created by Scheduler Agent", 90),
                ("KPIs generated by Analytics Agent", 100)
            ]
            for msg, pct in steps:
                if status_callback:
                    status_callback(msg, pct)
                time.sleep(0.3)

            # Retrieve realistic sample outputs
            if "campus brew" in campaign_reqs.get("product_name", "").lower():
                result = get_campus_brew_demo()
            else:
                result = generate_generic_demo(campaign_reqs)
            
            result["is_demo"] = True
            return result

        # --- LIVE AGENTIC PIPELINE EXECUTION ---
        try:
            # Step 1: Requirements Analysis
            if status_callback:
                status_callback("✓ Campaign requirements analyzed", 15)

            # Step 2: Audience Analysis Agent
            if status_callback:
                status_callback("Analyzing target audience (Audience Agent)...", 30)
            audience_res = self.audience_agent.run(campaign_reqs)
            if status_callback:
                status_callback("✓ Target audience analyzed", 35)

            # Step 3: Marketing Strategy Agent
            if status_callback:
                status_callback("Formulating creative campaign strategy (Strategy Agent)...", 45)
            strategy_res = self.strategy_agent.run(campaign_reqs, audience_res)
            if status_callback:
                status_callback("✓ Strategy generated", 50)

            # Step 4: Content Agent
            if status_callback:
                status_callback("Writing post copy & hooks (Content Agent)...", 60)
            content_res = self.content_agent.run(campaign_reqs, audience_res, strategy_res)
            if status_callback:
                status_callback("✓ Content generated", 65)

            # Step 5: Budget Agent
            if status_callback:
                status_callback("Optimizing budget allocation (Budget Agent)...", 75)
            budget_res = self.budget_agent.run(campaign_reqs, strategy_res)
            if status_callback:
                status_callback("✓ Budget allocated", 80)

            # Step 6: Scheduler Agent
            if status_callback:
                status_callback("Building campaign calendar (Scheduler Agent)...", 85)
            schedule_res = self.scheduler_agent.run(campaign_reqs, strategy_res, content_res)
            if status_callback:
                status_callback("✓ Schedule created", 90)

            # Step 7: KPI / Analytics Agent
            if status_callback:
                status_callback("Recommending target KPIs (Analytics Agent)...", 95)
            kpi_res = self.kpi_agent.run(campaign_reqs, budget_res)
            if status_callback:
                status_callback("✓ KPIs generated", 100)

            # Synthesize final master output structure
            master_plan = {
                "requirements": campaign_reqs,
                "audience": audience_res,
                "strategy": strategy_res,
                "content": content_res,
                "budget": budget_res,
                "schedule": schedule_res,
                "kpis": kpi_res,
                "is_demo": False
            }
            return master_plan

        except Exception as e:
            # Fallback gracefully to demo mode on unexpected API failure
            if status_callback:
                status_callback(f"⚠️ Live API issue: {str(e)}. Falling back to Demo Mode...", 100)
            result = generate_generic_demo(campaign_reqs)
            result["is_demo"] = True
            result["error_note"] = str(e)
            return result
